### ISSUE TITLE
Code style: Make code flake8 and black compatible.

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#327]
New and recently changed code is already flake8 and black compatible. Some code is not yet. In addition to flake8 and black type hints should be included.

After the code is compatible flake8 and black should be run in Travis as well.

**Comment by gcaria** [comment]
Hi, beginner willing to help here.
I'm working on this, and in the part where I'm fixing flake8 issues manually,
I see really a lot of `F541 f-string is missing placeholders`.

It seems to me that in those cases one can just make it a simple string.

**Comment by Hagellach37** [comment]
Hey @gcaria,
sorry for this late reply. We are a small team and a lot of things are going on at the same time. :) It's nice that you took a look at this issue. If there is anything not clear to you, I'm happy to guide you through some parts of the code.

**Comment by gcaria** [comment]
@Hagellach37  my pleasure, it's great to be able to help !

Since I'm at the stage the fixes for the flake8 warnings are potentially meaning-changing edits,
I want to make sure my changes are fine with you guys.

The warnings are mostly of these two types:
`E501 line too long`
`F541 f-string is missing placeholders`

For `E501`, the fix is easy for a comment-line, while in some instances the line just can't be shortened (at least with my knowledge) without rewriting the offending block of code, so I plan to just leave some lines as they are.
For `F541`, I plan to just remove the f in front of the string.

Would this be OK ?

**Comment by Hagellach37** [comment]
Hey,
this sounds great. Feel free to go along your proposed way. If comment lines can be shortened or split that's fine. If it is code lines that are too long we can leave them as they are, if there is no obvious solution (which I'm often times also not aware of).

:)

**Comment by Matthias-Schaub** [comment]
Thanks to the work of @gcaria all the code is now Black and flake8 compatible (#415). 
From now on the code will be checked for style through pre-commit and travis using Black, flake8 and Isort.
