### ISSUE TITLE
Send a notification to Slack when a project reaches 100% progress

### ISSUE THREAD

**Issue by laurentS** [mapswipe/python-mapswipe-workers#330]
It should be fairly easy to send a notification from the firebase `incProjectProgress` function when progress reaches a given threshold:
- 90% progress: notify project manager channel that a project is almost complete, make sure there are more in the pipeline
- 100%: notify project managers they can replace the project with a new one

The only trick is to prevent sending messages more than once, so some sort of flag needs to be stored somewhere. It could simply be in the project object in firebase, like `notification_90_sent: true` once it's sent, and nothing before (so no need to change the project creation).

The code could either run in the progress update function, or as a "cron" job, checking progress of all projects every N minutes.

**Comment by Hagellach37** [comment]
The back end workers are already calculating the progress for all active projects around every 15 minutes. So we have the information needed also in the back end and not only in firebase.

I like the idea of having the flag in firebase as an attribute of the project. We might not even need to set it up on project creation, since we can just assume that we didn't reach 90% or 100% when the attribute is missing.
