### ISSUE TITLE
users per project as api endpoint

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#335]
It would be cool for project managers to have a way to display users stats across projects.

Maybe two options:
* add a user stats endpoint to the api, e.g. having the user_id as a key and then their project stats, similar to what we have in the leadboard.
* or doing it on a per project basis and adding all user ids and how much they contributed.

attributes:
* user_id
* total_contributions
* groups_completed

optional attributes
* agreement score (this would be interesting, e.g. give a value to measure the overall agreement of this users ratings with the majority vote, or count how many confirming results there have been from other users.)

**Comment by Jorieke** [comment]
At this moment one can see these statistics on the number of contributors per project. It would be great to know (or be able to calculate) the number of swipers as well for the whole campaign. 

There were 20 swipers for this project: https://mapswipe.org/project.html?projectId=-M0Yh-1mBthIeHb6WpKl For the two other projects in the campaign it were 62 and 28 swipers. However I cannot assume that the total number of people is just the sum of these numbers, since 1 person might have contributed to all 3 projects.

**Comment by Hagellach37** [comment]
this is on it's way: output will look tike this. @Jorieke is this what you are looking for?


idx | project_id | user_id | groups_completed | total_contributions | agreeing_contributions | disagreeing_contributions | simple_agreement_score
-- | -- | -- | -- | -- | -- | -- | --
0 | build_area_default_with_bing | CWkgnstlmLSZc2un0BsZmf25OOH2 | 5 | 447 | 566 | 142 | 0.799435028248588
1 | build_area_default_with_bing | EpwqH6rq1XdINLpB4yr69E4HE0x2 | 3 | 165 | 66 | 21 | 0.758620689655172
2 | build_area_default_with_bing | X0zTSyvY0khDfRwc99aQfIjTEPK2 | 11 | 825 | 628 | 167 | 0.789937106918239
3 | build_area_default_with_bing | b7AC74KVsqRf8EAFRVY6hnKnmuf2 | 4 | 345 | 430 | 92 | 0.823754789272031
