### ISSUE TITLE
remove tile url from tasks in firebase

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#344]
Removing the `url` for tasks in firebase, could reduce overall storage in firebase and the data needed to transfer.

For projects which use 2 urls (e.g. completeness, change detection) this can reduce the size of the tasks about 50%. (e.g. 150kb with urls and 75kb without urls).

The urls can be build from the tile coordinates and the tile server information we already store in firebase for the projects.

In firebase you pay for the outgoing bandwith.
https://firebase.google.com/pricing/?gclid=EAIaIQobChMI0Ln6t8Ci6QIVFeJ3Ch1XPAb3EAAYASAAEgJu0_D_BwE

**Comment by Hagellach37** [comment]
the new version `2.0.4` of the MapSwipe client has been releases. This version does not require the tasks in Firebase. 

We have to wait untill all users adopted this or a later version before we can remove the tasks endpoint in Firebase entirely.

**Comment by Hagellach37** [comment]
@laurentS can you provide some insights on this. :) How many app versions do we stillt have that rely on the tasks being available in firebase?

Ideally I would like to remove this, since there is also a cost attached to the storing data in firebase.

**Comment by laurentS** [comment]
Good question. Just looked at analytics, and if we're looking for users still on version < 2.0.4, it looks like there were a maximum of 25 active users with app versions older than 2.0.4 in the last 30 days. Interestingly they all seem to be on iOS, which I find confusing. Given that it's less than 1% of the user base, and that I don't think we can send them a notification (because the app doesn't handle them before 2.0.4), I see 2 options:
- add an announcement text in the database, all users will see it, so it will be 99% useless, but likely to be seen so at least some of the targeted users. The limitation is that text in there can only be very short, but we can link to a short explanation in a github comment or something.
- do nothing, turn off the urls, let users crash and hope that they think about upgrading the app instead of uninstalling it
