### ISSUE TITLE
transfer results from firebase to mysql

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#38]
we need to add this to the BaseFuntions.

**Comment by maze2point0** [comment]
In order to get a as much as possible generic transfer of results, we will implement the new mysql structure(#42) for the results in firebase as well. The described base attributes will represent an own field in csv and mysql each. 
Results like integer or other result types will be represented in a json form. So the overall table structure for results in mysql stays the same for every kind of project for now.
