### ISSUE TITLE
progress notification: TypeError: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#394]
occurs when the project is not in firebase anymore.

**Comment by laurentS** [comment]
I'd suggest you look at type annotations for your python code, `mypy` typically picks up errors like this as you write them (if you integrate it with your code editor). On my other projects, I've found annotations to be incredibly helpful, both to pick up errors, but also to help understand what the code does, because you get hints about what a variable contains.

If I've already said this before, sorry for the repetition ;)

**Comment by Hagellach37** [comment]
was related to a value not being available in firebase. anyway, mypy will be useful. :)
