### ISSUE TITLE
Clarification for GDAL version

### ISSUE THREAD

**Issue by mathcass** [mapswipe/python-mapswipe-workers#9]
It looks like the version for [GDAL is pretty old](https://github.com/mapswipe/python-mapswipe-workers/blob/master/requirements.txt#L1) compared with what is [available](https://trac.osgeo.org/gdal/wiki/DownloadSource). Is there a specific reason for keeping it at this version?

**Comment by Hagellach37** [comment]
No. There is no specific reason for this. We are using very basic gdal functions to read/write files and for intersections.

**Comment by mathcass** [comment]
Got it. Do you think we should update? I can't seem to find much information on the main differences between v1 and v2 and I'm not sure what they're aiming for with respect to improvements. 

On one hand, it's good to have the latest versions because it ensures that most bugs are fixed and you get newer features. On the other hand if we don't need the new features and there are no bugs we've encountered. 

I tend to prefer auditing dependencies regularly and at least inspecting whether upgrading is easy (and weighing the positives and negatives of them). 

What's your opinion on version here? What do you tell students? If it's not important, please feel free to close this out (but we can clarify this in the requirements.txt)

**Comment by ericboucher** [comment]
Do we even need to pip install GDAL? I’ve had a lot of issues to install docker because of it and at first glance it doesn’t seem too useful for what we are doing. Thoughts @hagellach37?

Eric Boucher

**Comment by mathcass** [comment]
I'm interested in knowing @Hagellach37's thoughts on alternatives (and ways to do what GDAL provides without importing it), but we're definitely using it via the [`ogr` module](https://github.com/mapswipe/python-mapswipe-workers/search?utf8=%E2%9C%93&q=ogr&type=) it installs

From what I see, we're using

* ogr.Geometry
* ogr.wkbLinearRing
* ogr.GetDriverByName

and my guess is that some of this is for reading KML files that the input relies on. 

---

**Disclaimer**: I am not an expert on GDAL

**Comment by Hagellach37** [comment]
Hey,
at the moment we're using the ogr module only during the import of new projects.
And @mathcass you're correct, `ogr.GetDriverByName` is used to import the kml strings and get a geometry out of what the users provided. We are also using ogr functions in `create_groups`. We create the tile geometries. for doing so we create a linar ring and then add it to a polygon. We are also using an intersect function in this workflow.

The big advantage of using ogr is the flexibility regarding the input data type. (Right from the beginning our import script supported input as kml, shapefile or geojson.) However, we never used this flexibility, since users can only upload kml files.

There are also other pyhon libraries we could use. [Shapely](http://shapely.readthedocs.io/en/stable/manual.html) offers all the functionality we need to create the groups. But shapely only deals with geometries, we can't store a geojson file with attributes etc. out of the box. Furthermore, we would have to think about how to import kml files in shapely, we probably need the [fastkml library](https://github.com/cleder/fastkml) for this.

At the moment, I still have no clear position what would be best for the future. I like to use ogr because it offers everything I need, although it's a bit more complex. But I also agree, that we use only a small fraction of ogr's advantages.
