### ISSUE TITLE
Add a similar project name validation check in Manager Dashboard

### ISSUE THREAD

**Issue by Shhhhhubh** [mapswipe/python-mapswipe-workers#929]
The issue is similar to #678 and the solutions are the same.

**Comment by kopitek8** [comment]
Conversation from Slack: https://mapswipe.slack.com/archives/C0HCW2CJJ/p1716959437773869

**Comment by kopitek8** [comment]
## Update

We have fixed the validation for unique project title while creating new projects; it will work on new projects only. 

## Up Next

We need to write a cloud function as it is critical to migrate all the project data to add validation to all the old data. Additionally, we need to make a plan to back up the data before migrating all the old projects.

## Status Update

This issue is in halt for now as it now touches the data aspect of MapSwipe and it is critical. It will be resumed after the accessibility issue is done.
